os:
    - linux
    - osx
sudo: required
dist: trusty
language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - tree
before_install:
    - 'brew update || true'
    - 'brew install tree xz || true'
script:
    - 'curl -s -L https://github.com/sustrik/libmill/archive/master.tar.gz | tar -zxf -'
    - 'mv libmill-master libmill'
    - 'cd libmill'
    - 'libtoolize || true'
    - './autogen.sh'
    - './configure --enable-shared=false'
    - 'make'
    - 'cd ../'
    - 'mkdir -p m4'
    - 'autoreconf -if'
    - 'export CPPFLAGS=-I$(pwd)/libmill'
    - 'export LDFLAGS=-L$(pwd)/libmill/.libs'
    - '[[ $(uname) == "Darwin" ]] || export LIBS=-lrt'
    - './configure --prefix=/usr --sysconfdir=/etc'
    - 'make'
    - 'make check'
    - 'make DESTDIR=$(pwd)/dist/ install'
    - 'tree $(pwd)/dist/'
    - 'make dist'
    - 'make dist-xz'
    - 'make dist-zip'
